CREATE TABLE tasks
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1000),
    due_date     date,
    is_completed BOOLEAN,
    priority     INTEGER,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD email VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);


CREATE TABLE weather_snapshots
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city         VARCHAR(255),
    temperature  DOUBLE PRECISION,
    weather      VARCHAR(255),
    retrieved_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_weather_snapshots PRIMARY KEY (id)
);


ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD email VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);


CREATE TABLE weather_snapshots
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city         VARCHAR(255),
    temperature  DOUBLE PRECISION,
    weather      VARCHAR(255),
    retrieved_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_weather_snapshots PRIMARY KEY (id)
);